from typing import Any

def _batched_op_msg(*args, **kwargs) -> Any: ...
def _batched_write_command(*args, **kwargs) -> Any: ...
def _do_batched_insert(*args, **kwargs) -> Any: ...
def _encode_batched_op_msg(*args, **kwargs) -> Any: ...
def _encode_batched_write_command(*args, **kwargs) -> Any: ...
def _get_more_message(*args, **kwargs) -> Any: ...
def _insert_message(*args, **kwargs) -> Any: ...
def _op_msg(*args, **kwargs) -> Any: ...
def _query_message(*args, **kwargs) -> Any: ...
def _update_message(*args, **kwargs) -> Any: ...
