from typing import Any

from pymongo import common as common
from pymongo.common import validate_boolean as validate_boolean
from pymongo.compression_support import CompressionSettings as CompressionSettings
from pymongo.errors import ConfigurationError as ConfigurationError
from pymongo.pool import PoolOptions as PoolOptions
from pymongo.read_concern import ReadConcern as ReadConcern
from pymongo.read_preferences import make_read_preference as make_read_preference
from pymongo.read_preferences import read_pref_mode_from_name as read_pref_mode_from_name
from pymongo.server_selectors import any_server_selector as any_server_selector
from pymongo.ssl_support import get_ssl_context as get_ssl_context
from pymongo.write_concern import WriteConcern as WriteConcern

class ClientOptions:
    def __init__(self, username: Any, password: Any, database: Any, options: Any) -> None: ...
    @property
    def connect(self): ...
    @property
    def codec_options(self): ...
    @property
    def credentials(self): ...
    @property
    def local_threshold_ms(self): ...
    @property
    def server_selection_timeout(self): ...
    @property
    def server_selector(self): ...
    @property
    def heartbeat_frequency(self): ...
    @property
    def pool_options(self): ...
    @property
    def read_preference(self): ...
    @property
    def replica_set_name(self): ...
    @property
    def write_concern(self): ...
    @property
    def read_concern(self): ...
    @property
    def retry_writes(self): ...
    @property
    def retry_reads(self): ...
    @property
    def auto_encryption_opts(self): ...
