from typing import Any, Optional

from pymongo import common as common

class CollationStrength:
    PRIMARY: int = ...
    SECONDARY: int = ...
    TERTIARY: int = ...
    QUATERNARY: int = ...
    IDENTICAL: int = ...

class CollationAlternate:
    NON_IGNORABLE: str = ...
    SHIFTED: str = ...

class CollationMaxVariable:
    PUNCT: str = ...
    SPACE: str = ...

class CollationCaseFirst:
    UPPER: str = ...
    LOWER: str = ...
    OFF: str = ...

class Collation:
    def __init__(
        self,
        locale: Any,
        caseLevel: Optional[Any] = ...,
        caseFirst: Optional[Any] = ...,
        strength: Optional[Any] = ...,
        numericOrdering: Optional[Any] = ...,
        alternate: Optional[Any] = ...,
        maxVariable: Optional[Any] = ...,
        normalization: Optional[Any] = ...,
        backwards: Optional[Any] = ...,
        **kwargs: Any,
    ) -> None: ...
    @property
    def document(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

def validate_collation_or_none(value: Any): ...
