from typing import Any

def validate_compressors(dummy: Any, value: Any): ...
def validate_zlib_compression_level(option: Any, value: Any): ...

class CompressionSettings:
    compressors: Any = ...
    zlib_compression_level: Any = ...
    def __init__(self, compressors: Any, zlib_compression_level: Any) -> None: ...
    def get_compression_context(self, compressors: Any): ...

class SnappyContext:
    compressor_id: int = ...
    @staticmethod
    def compress(data: Any): ...

class ZlibContext:
    compressor_id: int = ...
    compress: Any = ...
    def __init__(self, level: Any): ...

class ZstdContext:
    compressor_id: int = ...
    @staticmethod
    def compress(data: Any): ...

def decompress(data: Any, compressor_id: Any): ...
