from typing import Any, Optional

from pymongo.collation import validate_collation_or_none as validate_collation_or_none
from pymongo.common import validate_boolean as validate_boolean
from pymongo.common import validate_is_mapping as validate_is_mapping
from pymongo.common import validate_list as validate_list

class InsertOne:
    def __init__(self, document: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class DeleteOne:
    def __init__(self, filter: Any, collation: Optional[Any] = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class DeleteMany:
    def __init__(self, filter: Any, collation: Optional[Any] = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class ReplaceOne:
    def __init__(self, filter: Any, replacement: Any, upsert: bool = ..., collation: Optional[Any] = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class _UpdateOp:
    def __init__(self, filter: Any, doc: Any, upsert: Any, collation: Any, array_filters: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class UpdateOne(_UpdateOp):
    def __init__(
        self,
        filter: Any,
        update: Any,
        upsert: bool = ...,
        collation: Optional[Any] = ...,
        array_filters: Optional[Any] = ...,
    ) -> None: ...

class UpdateMany(_UpdateOp):
    def __init__(
        self,
        filter: Any,
        update: Any,
        upsert: bool = ...,
        collation: Optional[Any] = ...,
        array_filters: Optional[Any] = ...,
    ) -> None: ...

class IndexModel:
    def __init__(self, keys: Any, **kwargs: Any) -> None: ...
    @property
    def document(self): ...
