from typing import Any, Optional

class PeriodicExecutor:
    def __init__(self, interval: Any, min_interval: Any, target: Any, name: Optional[Any] = ...) -> None: ...
    def open(self) -> None: ...
    def close(self, dummy: Optional[Any] = ...) -> None: ...
    def join(self, timeout: Optional[Any] = ...) -> None: ...
    def wake(self) -> None: ...
    def update_interval(self, new_interval: Any) -> None: ...
