from typing import Any, Optional

class ReadConcern:
    def __init__(self, level: Optional[Any] = ...) -> None: ...
    @property
    def level(self): ...
    @property
    def ok_for_legacy(self): ...
    @property
    def document(self): ...
    def __eq__(self, other: Any) -> Any: ...

DEFAULT_READ_CONCERN: Any
