from typing import Any

class SONManipulator:
    def will_copy(self): ...
    def transform_incoming(self, son: Any, collection: Any): ...
    def transform_outgoing(self, son: Any, collection: Any): ...

class ObjectIdInjector(SONManipulator):
    def transform_incoming(self, son: Any, collection: Any): ...

class ObjectIdShuffler(SONManipulator):
    def will_copy(self): ...
    def transform_incoming(self, son: Any, collection: Any): ...

class NamespaceInjector(SONManipulator):
    def transform_incoming(self, son: Any, collection: Any): ...

class AutoReference(SONManipulator):
    database: Any = ...
    def __init__(self, db: Any) -> None: ...
    def will_copy(self): ...
    def transform_incoming(self, son: Any, collection: Any): ...
    def transform_outgoing(self, son: Any, collection: Any): ...
