from typing import Any, Optional

from pymongo.common import CONNECT_TIMEOUT as CONNECT_TIMEOUT
from pymongo.errors import ConfigurationError as ConfigurationError

def maybe_decode(text: Any): ...

class _SrvResolver:
    def __init__(self, fqdn: Any, connect_timeout: Optional[Any] = ...) -> None: ...
    def get_options(self): ...
    def get_hosts(self): ...
    def get_hosts_and_min_ttl(self): ...
