from typing import Any, Optional

from pymongo.errors import ConfigurationError as ConfigurationError

class WriteConcern:
    def __init__(
        self, w: Optional[Any] = ..., wtimeout: Optional[Any] = ..., j: Optional[Any] = ..., fsync: Optional[Any] = ...
    ) -> None: ...
    @property
    def is_server_default(self): ...
    @property
    def document(self): ...
    @property
    def acknowledged(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

DEFAULT_WRITE_CONCERN: Any
